# .pre-commit-config.yaml
repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0  # Use a versão estável mais recente
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0  # Use a versão estável mais recente
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0  # Use a versão estável mais recente
    hooks:
      - id: flake8

  - repo: local
    hooks:
      - id: django-tests
        name: Run Django tests
        entry: python manage.py test
        language: system
        pass_filenames: false
        stages: [commit]
