# Generated by Django 4.2.15 on 2024-08-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_donativo_donation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donativo',
        ),
        migrations.AlterModelOptions(
            name='congregation',
            options={'verbose_name': 'Congregação', 'verbose_name_plural': 'Congregações'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
